import { FormEvent, useEffect, useMemo, useState } from "react"
import { pagesApi } from "../api/pages"
import { defaultReleaseBlocks, ReleaseSummary } from "../components/ChangeLogContent"
import type { ChangeLogPage, ChangeLogRecord, ReleaseBlock, ReleaseBlockType } from "../types"

type Draft = Omit<ChangeLogPage, "id" | "created" | "updated">
type WizardStep = 1 | 2 | 3 | 4
const apiDefault = "https://api.tianyibrad.com/api/collections/OpenChangeLog/records"
const blockTypes: { value: ReleaseBlockType; label: string }[] = [{ value: "date", label: "Date" }, { value: "badge", label: "Badge" }, { value: "title", label: "Title" }, { value: "text", label: "Text" }, { value: "markdown", label: "Markdown content" }]
const defaultThemeCss = ".open-changelog-page { --oc-accent: #2563eb; }\n.open-changelog-page .brand-mark { background: var(--oc-accent); }"
const empty: Draft = { name: "", publicPath: "", apiUrl: "", releaseIdentifierField: "id", releaseBlocks: [], releaseMaxHeight: 260, apiTimeoutSeconds: 15, markdownCss: "", themeCss: "", brandName: "", logoUrl: "", websiteUrl: "", introLabel: "Product updates", introDescription: "Every release, improvement, and important fix in one place.", footerText: "Product updates", isHome: false }
const preview: ChangeLogRecord = { id: "preview", version: "0.1.0", title: "Your first release", content: "Use the blocks on the left to decide how every release summary is presented.", created: "2026-08-19T12:00:00.000Z", updated: "2026-08-19T12:00:00.000Z" }
function toDraft(page: ChangeLogPage): Draft { const { id, created, updated, ...value } = page; return { ...empty, ...value } }

function Wizard({ session, initial, onClose, onSaved }: { session: string; initial?: ChangeLogPage; onClose: () => void; onSaved: () => Promise<void> }) {
  const [step, setStep] = useState<WizardStep>(1)
  const [draft, setDraft] = useState<Draft>(initial ? toDraft(initial) : empty)
  const [fields, setFields] = useState<string[]>([])
  const [record, setRecord] = useState<ChangeLogRecord>(preview)
  const [message, setMessage] = useState("")
  const [saving, setSaving] = useState(false)
  const blocks = draft.releaseBlocks.length ? draft.releaseBlocks : defaultReleaseBlocks
  const displayFields = fields.filter((field) => field !== "collectionId" && field !== "collectionName")
  const dateFields = displayFields.filter((field) => !Number.isNaN(Date.parse(String(record[field] || ""))))
  const fieldsFor = (type: ReleaseBlockType) => type === "date" ? dateFields : displayFields
  const changeType = (id: string, type: ReleaseBlockType) => { const options = fieldsFor(type); changeBlock(id, { type, field: options.includes(blocks.find((block) => block.id === id)?.field || "") ? blocks.find((block) => block.id === id)?.field : options[0] || "" }) }
  const goToStep = (next: WizardStep) => { if (next === 2 && !fields.length) { inspect(); return } if (next > 2 && !fields.length) { setMessage("Verify the API before opening later steps."); return } setStep(next) }
  const inspect = async () => { try { setMessage(""); const result = await pagesApi.inspect(draft.apiUrl, session); if (!result.fields.length) throw new Error("The API returned no records to inspect"); setFields(result.fields); if (result.sample) setRecord(result.sample); const available = result.fields.filter((field) => field !== "collectionId" && field !== "collectionName"); const dates = available.filter((field) => !Number.isNaN(Date.parse(String(result.sample?.[field] || "")))); setDraft((value) => { const source = value.releaseBlocks.length ? value.releaseBlocks : defaultReleaseBlocks; const releaseBlocks = source.map((block) => { const allowed = block.type === "date" ? dates : available; if (allowed.includes(block.field)) return block; return { ...block, type: block.type === "date" && !dates.length ? "text" : block.type, field: (allowed.length ? allowed : available)[0] || "" } }).filter((block) => block.field); return { ...value, releaseBlocks, releaseIdentifierField: available.includes(value.releaseIdentifierField) ? value.releaseIdentifierField : (available.includes("id") ? "id" : available[0] || "") } }); setStep(2) } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to verify API") } }
  const changeBlock = (id: string, patch: Partial<ReleaseBlock>) => setDraft((value) => ({ ...value, releaseBlocks: blocks.map((block) => block.id === id ? { ...block, ...patch } : block) }))
  const moveBlock = (index: number, direction: -1 | 1) => setDraft((value) => { const next = [...blocks]; const target = index + direction; if (target < 0 || target >= next.length) return { ...value, releaseBlocks: next }; [next[index], next[target]] = [next[target], next[index]]; return { ...value, releaseBlocks: next } })
  const save = async () => { try { setSaving(true); if (initial) await pagesApi.update(initial.id, draft, session); else await pagesApi.create(draft, session); await onSaved(); onClose() } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save page") } finally { setSaving(false) } }
  return <section className="setup-wizard" aria-label="Changelog setup wizard"><div className="wizard-top"><div><span className="component-label">{initial ? "Edit changelog" : "New changelog"}</span><h2>{step === 1 ? "Start with the connection" : step === 2 ? "Arrange each release" : step === 3 ? "Make it yours" : "Finish the presentation"}</h2></div><button className="text-button" onClick={onClose}>Cancel</button></div><ol className="wizard-progress">{["Page", "Layout", "Brand", "CSS"].map((label, index) => <li key={label} className={index + 1 === step ? "active" : index + 1 < step ? "done" : ""}><button type="button" onClick={() => goToStep((index + 1) as WizardStep)}><span>{index + 1}</span>{label}</button></li>)}</ol><div className="wizard-stage" key={step}>
    {step === 1 && <div className="wizard-form"><p>Choose a public path and verify a PocketBase records endpoint before configuring its presentation.</p><label>Page name <b>*</b><input required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="Product updates" /></label><label>Public path <b>*</b><input required value={draft.publicPath} onChange={(event) => setDraft({ ...draft, publicPath: event.target.value.replace(/^\/+|\/+$/g, "") })} placeholder="updates" /></label><label className="home-choice"><input type="checkbox" checked={draft.isHome} onChange={(event) => setDraft({ ...draft, isHome: event.target.checked })} /><span><strong>Use as the home changelog</strong><small>Visitors at the site root will open this page.</small></span></label><label>PocketBase records API <b>*</b><input required type="url" value={draft.apiUrl} placeholder={apiDefault} onChange={(event) => setDraft({ ...draft, apiUrl: event.target.value })} /></label><label>Timeout time <span className="field-help">Seconds to wait for the records API before showing an error.</span><input type="number" min="1" max="60" value={draft.apiTimeoutSeconds} onChange={(event) => setDraft({ ...draft, apiTimeoutSeconds: Math.max(1, Math.min(60, Number(event.target.value) || 1)) })} /></label><p className="wizard-hint">The next step verifies this endpoint and reads its first record.</p></div>}
    {step === 2 && <div className="wizard-layout"><div><p>Fields were read from the connected API. Select a block type and field, then set the order visitors should see.</p><label className="url-field">Maximum summary height <span className="field-help">Maximum height of each release on the list, in pixels.</span><input type="number" min="120" max="800" value={draft.releaseMaxHeight} onChange={(event) => setDraft({ ...draft, releaseMaxHeight: Math.max(120, Math.min(800, Number(event.target.value) || 120)) })} /></label><label className="url-field">Release URL field<select value={draft.releaseIdentifierField} onChange={(event) => setDraft({ ...draft, releaseIdentifierField: event.target.value })}>{displayFields.map((field) => <option key={field} value={field}>{field}</option>)}</select></label><div className="wizard-blocks">{blocks.map((block, index) => <article className="wizard-block" key={block.id}><div className="block-order"><button disabled={index === 0} onClick={() => moveBlock(index, -1)} aria-label="Move block up">Up</button><button disabled={index === blocks.length - 1} onClick={() => moveBlock(index, 1)} aria-label="Move block down">Down</button></div><label>Block type<select value={block.type} onChange={(event) => changeType(block.id, event.target.value as ReleaseBlockType)}>{blockTypes.map((type) => <option key={type.value} disabled={type.value === "date" && !dateFields.length} value={type.value}>{type.label}</option>)}</select></label><label>Record field<select value={block.field} onChange={(event) => changeBlock(block.id, { field: event.target.value })}>{fieldsFor(block.type).map((field) => <option key={field} value={field}>{field}</option>)}</select></label><button className="text-button remove-block" onClick={() => setDraft({ ...draft, releaseBlocks: blocks.filter((item) => item.id !== block.id) })}>Remove</button></article>)}</div><button className="secondary-button" disabled={!displayFields.length} onClick={() => setDraft({ ...draft, releaseBlocks: [...blocks, { id: crypto.randomUUID(), type: "text", field: displayFields[0] || "" }] })}>Add block</button></div><aside className="wizard-preview"><span className="component-label">Live API preview</span><article className="changelog-entry"><ReleaseSummary entry={record} blocks={blocks} maxHeight={draft.releaseMaxHeight} /></article></aside></div>}
    {step === 3 && <div className="wizard-form wizard-brand"><p>These values appear in the public header, footer, and browser tab.</p><label>Brand name<input value={draft.brandName} onChange={(event) => setDraft({ ...draft, brandName: event.target.value })} placeholder={draft.name || "What's New"} /></label><label>Logo image URL<input type="url" value={draft.logoUrl} onChange={(event) => setDraft({ ...draft, logoUrl: event.target.value })} placeholder="https://example.com/logo.png" /></label><label>Website URL<input type="url" value={draft.websiteUrl} onChange={(event) => setDraft({ ...draft, websiteUrl: event.target.value })} placeholder="https://example.com" /></label><label>Intro label<input value={draft.introLabel} onChange={(event) => setDraft({ ...draft, introLabel: event.target.value })} /></label><label>Intro description<textarea value={draft.introDescription} onChange={(event) => setDraft({ ...draft, introDescription: event.target.value })} /></label><label>Footer text<input value={draft.footerText} onChange={(event) => setDraft({ ...draft, footerText: event.target.value })} /></label></div>}
    {step === 4 && <div className="wizard-css"><div><p>Optional. Changes render immediately in this preview and are saved with this page only.</p><label>Page theme CSS<textarea value={draft.themeCss} onChange={(event) => setDraft({ ...draft, themeCss: event.target.value })} placeholder={defaultThemeCss} /></label><label>Markdown CSS<textarea value={draft.markdownCss} onChange={(event) => setDraft({ ...draft, markdownCss: event.target.value })} placeholder=".changelog-content h2 { color: #2563eb; }" /></label></div><aside className="wizard-css-preview open-changelog-page"><style>{draft.themeCss}</style><style>{draft.markdownCss}</style><header className="site-header"><span className="brand"><img className="brand-logo" src={draft.logoUrl || '/logo.png'} alt="" /><span>{draft.brandName || draft.name || "Your brand"}</span></span></header><div className="css-preview-content"><p className="eyebrow">{draft.introLabel}</p><h2>{draft.name || "Product updates"}</h2><article className="changelog-entry"><ReleaseSummary entry={record} blocks={blocks} maxHeight={draft.releaseMaxHeight} /></article></div></aside></div>}
  </div>{message && <p className="error-notice">{message}</p>}<div className="wizard-actions">{step > 1 && <button className="secondary-button" onClick={() => setStep((step - 1) as WizardStep)}>Back</button>}{step < 4 ? <button className="primary-button" disabled={step === 1 && (!draft.name || !draft.publicPath || !draft.apiUrl)} onClick={() => step === 1 ? inspect() : setStep((step + 1) as WizardStep)}>{step === 1 ? "Verify API and continue" : "Continue"}</button> : <button className="primary-button" disabled={saving} onClick={save}>{saving ? "Saving..." : initial ? "Save changes" : "Create changelog"}</button>}</div></section>
}

export function AdminPage({ section = "pages" }: { section?: "pages" | "theme" }) {
  const [session, setSession] = useState(() => sessionStorage.getItem("open-changelog-admin-session") || "")
  const [password, setPassword] = useState("")
  const [pages, setPages] = useState<ChangeLogPage[]>([])
  const [wizardPage, setWizardPage] = useState<ChangeLogPage | undefined>()
  const [showWizard, setShowWizard] = useState(false)
  const [themePageId, setThemePageId] = useState("")
  const [themeCss, setThemeCss] = useState("")
  const [message, setMessage] = useState("")
  const selectedThemePage = useMemo(() => pages.find((page) => page.id === themePageId) || pages[0], [pages, themePageId])
  const load = async () => { try { const next = await pagesApi.list(session); setPages(next); if (!themePageId && next[0]) { setThemePageId(next[0].id); setThemeCss(next[0].themeCss || defaultThemeCss) } setMessage("") } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load pages") } }
  useEffect(() => { if (session) load() }, [session])
  useEffect(() => { if (selectedThemePage) setThemeCss(selectedThemePage.themeCss || defaultThemeCss) }, [selectedThemePage?.id])
  const login = async (event: FormEvent) => { event.preventDefault(); try { const result = await pagesApi.login(password); sessionStorage.setItem("open-changelog-admin-session", result.token); setSession(result.token) } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to sign in") } }
  const saveTheme = async () => { if (!selectedThemePage) return; try { await pagesApi.update(selectedThemePage.id, { ...toDraft(selectedThemePage), themeCss }, session); await load(); setMessage("Theme CSS saved") } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save theme CSS") } }
  const remove = async (page: ChangeLogPage) => { if (!confirm("Delete " + page.name + "?")) return; await pagesApi.remove(page.id, session); await load() }
  const logout = () => { sessionStorage.removeItem("open-changelog-admin-session"); setSession("") }
  if (!session) return <main className="admin-page"><section className="login-panel"><p className="eyebrow">Protected area</p><h1>Admin sign in</h1><p>Enter the configured ADMIN_PASSWORD.</p><form onSubmit={login}><label>Password<input autoFocus required type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><button className="primary-button">Sign in</button></form>{message && <p className="error-notice">{message}</p>}</section></main>
  return <main className="admin-page"><header className="admin-header"><a href="/" className="brand"><img className="brand-logo" src="/logo.png" alt="" /><span>What's New</span></a><div className="admin-nav"><a className={section === "pages" ? "active" : ""} href="/admin">Pages</a><button className="text-button" onClick={logout}>Sign out</button></div></header><div className="admin-shell">{section === "theme" ? <section className="theme-editor"><div className="admin-intro"><p className="eyebrow">Page theme</p><h1>Custom CSS</h1><p>Change styles for an existing public page.</p></div>{selectedThemePage && <><div className="theme-toolbar"><label>Changelog page<select value={selectedThemePage.id} onChange={(event) => setThemePageId(event.target.value)}>{pages.map((page) => <option key={page.id} value={page.id}>{page.name}</option>)}</select></label><button className="primary-button" onClick={saveTheme}>Save CSS</button></div><label className="theme-source"><span>Theme CSS</span><textarea value={themeCss} onChange={(event) => setThemeCss(event.target.value)} /></label></>}{message && <p className="error-notice">{message}</p>}</section> : <><section className="admin-intro"><p className="eyebrow">Changelog pages</p><h1>Publish a changelog</h1><p>Create each new public changelog through a guided setup flow.</p></section>{showWizard ? <Wizard session={session} initial={wizardPage} onClose={() => { setShowWizard(false); setWizardPage(undefined) }} onSaved={load} /> : <><div className="admin-command"><div><strong>New changelog</strong><span>Connection, release layout, brand, and optional CSS.</span></div><button className="primary-button" onClick={() => { setWizardPage(undefined); setShowWizard(true) }}>Create page</button></div><section className="admin-list"><h2>Configured pages</h2>{pages.map((page) => <article key={page.id} className="page-row"><div><h3>{page.name}</h3><a href={"/" + page.publicPath} target="_blank" rel="noreferrer">{location.origin + "/" + page.publicPath}</a></div><div className="row-actions"><button className="secondary-button" onClick={() => { setWizardPage(page); setShowWizard(true) }}>Edit</button><button className="danger-button" onClick={() => remove(page)}>Delete</button></div></article>)}{!pages.length && <p className="empty-state">No pages configured yet.</p>}</section></>}</>}</div></main>
}
