import { MouseEvent, useEffect, useMemo, useState } from 'react'
import { pagesApi } from './api/pages'
import { ChangeLogContent, ChangeLogEntry } from './components/ChangeLogContent'
import { AdminPage } from './pages/AdminPage'
import type { ChangeLogPage, ChangeLogRecord } from './types'

type Theme = 'light' | 'dark' | 'system'
function decodeSegment(value?: string) { try { return value ? decodeURIComponent(value) : undefined } catch { return value } }
function route(pathname: string) { const parts = pathname.split('/').filter(Boolean); return { full: parts.join('/'), candidatePath: parts.slice(0, -1).join('/'), releaseId: decodeSegment(parts.at(-1)) } }
function releaseIdentifier(entry: ChangeLogRecord, field: string) { const value = entry[field]; return typeof value === 'string' && value.trim() ? value.trim() : entry.id }
function useRouter() { const [pathname, setPathname] = useState(() => location.pathname); useEffect(() => { const onPopState = () => setPathname(location.pathname); addEventListener('popstate', onPopState); return () => removeEventListener('popstate', onPopState) }, []); const navigate = (path: string, state: Record<string, string> = {}) => { if (path === location.pathname) return; history.pushState(state, '', path); setPathname(path); scrollTo({ top: 0, behavior: 'smooth' }) }; return { pathname, navigate } }
function internalLink(path: string, navigate: (path: string, state?: Record<string, string>) => void, state?: Record<string, string>) { return (event: MouseEvent<HTMLAnchorElement>) => { if (event.button || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return; event.preventDefault(); navigate(path, state) } }

function PublicPage({ pathname, navigate }: { pathname: string; navigate: (path: string, state?: Record<string, string>) => void }) {
  const [page, setPage] = useState<ChangeLogPage | null>(null); const [entries, setEntries] = useState<ChangeLogRecord[]>([]); const [selected, setSelected] = useState<ChangeLogRecord | null>(null); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [theme, setTheme] = useState<Theme>(() => (localStorage.getItem('open-changelog-theme') as Theme) || 'system')
  useEffect(() => { const media = matchMedia('(prefers-color-scheme: dark)'); const apply = () => document.documentElement.dataset.theme = theme === 'system' ? (media.matches ? 'dark' : 'light') : theme; apply(); media.addEventListener('change', apply); localStorage.setItem('open-changelog-theme', theme); return () => media.removeEventListener('change', apply) }, [theme])
  useEffect(() => { let active = true; setLoading(true); setError(''); const current = route(pathname); (async () => { try { let found: ChangeLogPage; let detailId: string | undefined; try { found = await pagesApi.publicPage(current.full) } catch { found = await pagesApi.publicPage(current.candidatePath); detailId = current.releaseId } const records = page?.id === found.id ? entries : await pagesApi.records(found.id); if (!active) return; setPage(found); setEntries(records); setSelected(detailId ? records.find((entry) => releaseIdentifier(entry, found.releaseIdentifierField || 'id') === detailId) ?? null : null); setError('') } catch (requestError) { active && setError(requestError instanceof Error ? requestError.message : 'Unable to load changelog') } finally { if (active) setLoading(false) } })(); return () => { active = false } }, [pathname])
  useEffect(() => { if (!page) return; const brand = page.brandName || page.name || 'OpenChangeLog'; document.title = page.name && page.name !== brand ? page.name + ' | ' + brand : brand; let icon = document.querySelector('link[rel="icon"]') as HTMLLinkElement | null; if (!icon) { icon = document.createElement('link'); icon.rel = 'icon'; document.head.append(icon) } icon.href = page.logoUrl || '/logo.png' }, [page])
  useEffect(() => { if (selected) return; const releaseId = history.state?.restoreReleaseId; if (!releaseId || !entries.length) return; history.replaceState({ ...history.state, restoreReleaseId: undefined }, '', location.href); const frame = requestAnimationFrame(() => document.getElementById(`release-${releaseId}`)?.scrollIntoView({ block: 'center' })); return () => cancelAnimationFrame(frame) }, [selected, entries, pathname])
  const visible = useMemo(() => { const needle = query.toLowerCase().trim(); return needle ? entries.filter((entry) => `${entry.version} ${entry.title} ${entry.content}`.toLowerCase().includes(needle)) : entries }, [entries, query])
  const releaseLink = (entry: ChangeLogRecord) => '/' + page?.publicPath + '/' + encodeURIComponent(releaseIdentifier(entry, page?.releaseIdentifierField || 'id')); const homeLink = page ? `/${page.publicPath}` : '/'
  const openRelease = (entry: ChangeLogRecord) => { history.replaceState({ ...(history.state || {}), restoreReleaseId: entry.id }, '', location.href); navigate(releaseLink(entry)) }
  const introLabel = page?.introLabel || 'Product updates'; const introDescription = page?.introDescription || 'Every release, improvement, and important fix in one place.'; const footerText = page?.footerText || 'Product updates'; const brandName = page?.brandName || page?.name || 'OpenChangeLog'; const logoUrl = page?.logoUrl; const websiteUrl = page?.websiteUrl
  return <main className="open-changelog-page">{page?.themeCss && <style>{page.themeCss}</style>}{page?.markdownCss && <style>{page.markdownCss}</style>}<div className={loading ? 'route-progress is-loading' : 'route-progress'} aria-hidden="true" /><header className="site-header"><a className="brand" href={homeLink} onClick={internalLink(homeLink, navigate)}><img className="brand-logo" src={logoUrl || '/logo.png'} alt="" /><span>{brandName}</span></a><nav>{websiteUrl && <a className="brand-website" href={websiteUrl} target="_blank" rel="noreferrer">Website</a>}<button className="icon-button" onClick={() => setTheme((value) => value === 'light' ? 'dark' : value === 'dark' ? 'system' : 'light')} aria-label="Change color theme">{theme === 'dark' ? '☾' : theme === 'light' ? '☼' : '◐'}</button></nav></header><div className="shell">
    {error ? <p className="error-notice">{error}</p> : selected ? <section className="detail-view"><a className="back-button" href={homeLink} onClick={internalLink(homeLink, navigate, { restoreReleaseId: selected.id })}>← All updates</a><article className="detail-entry"><span className="version">{selected.version}</span><h1>{selected.title}</h1><ChangeLogContent content={selected.content} /><p className="permalink"><a href={releaseLink(selected)} onClick={internalLink(releaseLink(selected), navigate)}>{location.origin}{releaseLink(selected)}</a></p></article></section> : <><section className="intro"><p className="eyebrow">{introLabel}</p><h1>{page?.name || 'Loading updates'}</h1><p>{introDescription}</p></section><section className="search-row"><label htmlFor="search">Search updates</label><div className="search-input"><span>⌕</span><input id="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search versions and updates..." /></div></section><section className="release-list">{visible.map((entry) => <ChangeLogEntry key={entry.id} entry={entry} blocks={page?.releaseBlocks} maxLength={page?.releaseMaxLength} onOpen={() => openRelease(entry)} />)}{page && !visible.length && <p className="empty-state">No updates match your search.</p>}</section></>}
  </div><footer><span>{brandName}</span><span>{footerText}</span></footer></main>
}
export default function App() { const router = useRouter(); return router.pathname.startsWith('/admin') ? <AdminPage /> : <PublicPage {...router} /> }
